blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/jasjs1/Programmer-Netlink/blob/pages/.github/ISSUE_TEMPLATE/bugreport.md
    about: Report a bug for me to fix, and I will do my best to squash it!
