
blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/jasjs1/Programmer-Netlink/blob/pages/.github/ISSUE_TEMPLATE/BugReport.md
    about: Create a bug report
  - name: Feature Request
    url: https://github.com/jasjs1/Programmer-Netlink/blob/5bbe6738647a17cc2fb54b63020d322b871ca405/.github/ISSUE_TEMPLATE/FeatureRequest.md
    about: Create a feature that you would like to see in Programmer Netlink
